### ISSUE TITLE
Feature: Choose ID type

### ISSUE THREAD

**Issue by Anonynz** [Diegiwg/mycro-db#1]
From what I understand, it is not possible to choose the 'type' of data that will be used as an ID in a given collection. I would like this possibility to be added to the API.

Another thing, looking at the code that generates the collection, I saw that it 'automatically' / 'forcibly' attaches the Document ID to its record. Although I haven't messed up anything so far, I believe that doing this without the programmer explicitly stating that he wants to do so is shooting himself in the foot.

Anyway, I would like to have the choice of what type of data I will have as an ID, and for this automated ID system in the Document to be replaced by something less intrusive.

**Comment by Diegiwg** [comment]
The library aims to keep things simple and user-friendly, which is why it generates only one type of ID and automatically inserts it into documents. 😊

However, I totally get your concerns about having more flexibility and customization. 🤔

If you have a specific use case or scenario where customizing the ID type is really important, don't hesitate to share it with us! We might consider it for future updates. 🚀

Your feedback means a lot, and the project will keep growing thanks to the contributions and needs of the community. 🙌

Thanks for your understanding! 👍
